# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review_it', '0002_auto_20161002_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_of',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 21, 57, 56, 643762, tzinfo=utc)),
        ),
    ]
