# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_it', '0004_auto_20161002_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_by',
        ),
    ]
