# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_it', '0005_remove_review_review_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
